post http://localhost:3010/add-contact
Content-Type: application/json

{
    "email":"testtesttestfab10@free.fr",
    "name":"testfabfab",
    "campaignId":"Cd9Vu"
}

###
post https://email-server-api-production.up.railway.app/add-contact
Content-Type: application/json

{
    "email":"testapi2@free.fr",
    "name":"testfabfadsdsb",
    "campaignId":"qD1uT"
}